# Boilerplate
type Info {
  id: ID!
  name: String!
  description: String
}

type State {
  id: ID!
  val: Boolean!
}

type Action {
  id: ID!
  pre: [State!]!
  post: [State!]!
}

type Scenario {
  id: ID!
  goal: [State!]!
  state: [State!]!
  actions: [Action!]!
}

input StateInput {
  id: ID!
  val: Boolean!
}

input ActionInput {
  id: ID!
  pre: [StateInput!]!
  post: [StateInput!]!
}

input ScenarioInput {
  id: ID!
  goal: [StateInput!]!
  state: [StateInput!]!
  actions: [ActionInput!]!
}

type Plan {
  actions: [Action!]!
}

type Query {
  info: Info!
  plan(scenario: ScenarioInput!): Plan!
}

# Write your query or mutation here
query info {
  info {
    id
    name
  }
}
